version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: socialdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://yourusername:yourpassword@db:5432/socialdb
    depends_on:
      - db

volumes:
  postgres_data:

