version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: socialdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.production
    command: gunicorn app.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --workers 4 --timeout 120
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://yourusername:yourpassword@db:5432/socialdb
    depends_on:
      - db

volumes:
  postgres_data:

